### ISSUE TITLE
Some parts of api not working

### ISSUE THREAD

**Issue by LUMINARSFT** [amvstrm/api#17]
I found 2 errors in the deployed project.

**1.Vercel Error**
Project deployed successfully. But when trying to reach url below error appears.
```
**This Serverless Function has crashed.
Your connection is working correctly.
Vercel is working correctly.**
```

**2.Api stream not working**
Example url : https://api-amvstrm.nyt92.eu.org/api/v2/stream?id=jarinko-chie-tv-episode-10&data_src=gogo

```
404 Not Found
{
  "code": 404,
  "message": "Route not found"
}
```

**Comment by NYT92** [comment]
the ``?id=`` query used to be in the old api but now it switches from query to params.

![image](https://github.com/amvstrm/api/assets/53612429/a146979b-e898-4d0f-bf64-3ae0a0881222)

it should be like this
``
https://api-amvstrm.nyt92.eu.org/api/v2/stream/jarinko-chie-tv-episode-10
``

**Comment by LUMINARSFT** [comment]
Thank you very much for the reply. Don't you know how to fix vercel error?

**Comment by NYT92** [comment]
Can you show me your vercel log, deployment, and env config

**Comment by LUMINARSFT** [comment]
Thank you sir. It worked.
I appreciate your great help and amvstrm api. 😊
