### ISSUE TITLE
Adding more sources

### ISSUE THREAD

**Issue by OshekharO** [amvstrm/api#18]
How about adding some sources for movies, dramas like cdrama and kdrama, comics / manga and light novel? And some nsfw sources will be bonus.

It's just an request all depends on your choice 🙂.

**Comment by NYT92** [comment]
I plan to add more anime source but for cdrama, movie and other, I don't feel like adding it to my API because my whole project is about anime.

You can use @consumet extension or their API. They did a great job maintaining all of these.

**Comment by OshekharO** [comment]
Hmm, i didn't used consumet because they don't have any working api for movies, drama, novels. I checked almost all are broken or desolate.
