### ISSUE TITLE
/episode/:id route is returning an error

### ISSUE THREAD

**Issue by silverAndroid** [amvstrm/api#20]
I'm not sure if the route has changed or if I'm passing an incorrect ID so I can get the list of episodes for a title but passing in the Anilist ID isn't working anymore for some reason

https://api-amvstrm.nyt92.eu.org/api/v2/episode/97938 - example

**Comment by NYT92** [comment]
It seem like some data return and some don't. I will look into it.

**Comment by NYT92** [comment]
I think it the module fault because the module have to fetch many data and it is extremely slow and my server runtime can only run up to 20 seconds before it return 502 timeout. I might consider using Anify data.
