### ISSUE TITLE
Update the URL

### ISSUE THREAD

**Issue by TonyGamer** [amvstrm/api#22]
The current URL returns error 502. Switching to the updated URL seems to work perfectly fine

**Comment by adgsenpai** [comment]
@TonyGamer dude what is the new fucking URL. You can save my asshole by telling me that!

**Comment by Mekomancer** [comment]
![image](https://github.com/amvstrm/api/assets/79238580/b1eb39cd-32a6-41fb-879e-a5376aefc2c9)
![image](https://github.com/amvstrm/api/assets/79238580/7ef87da0-f95f-4304-a724-133e982872b3)

**Comment by adgsenpai** [comment]
> ![image](https://github.com/amvstrm/api/assets/79238580/b1eb39cd-32a6-41fb-879e-a5376aefc2c9)
> ![image](https://github.com/amvstrm/api/assets/79238580/7ef87da0-f95f-4304-a724-133e982872b3)
> @adgsenpai your asshole is saved

I'm talking about the streaming endpoint?

/api/v1/episode/one-piece

For example doesn't work?

**Comment by adgsenpai** [comment]
![Screenshot_20231129-055048_Samsung Internet.jpg](https://github.com/amvstrm/api/assets/45560312/86169928-923b-452d-ad3b-5e7a98768b7c)

My observation is that the streaming works but the episodes metadata doesn't work on the owners website?

That's fine I'll play around. I got the other GraphQL stuff giving me the data.

Thanks guys for letting me know.

**Comment by adgsenpai** [comment]
Wtf it seems like it's back up FFS ![Screenshot_20231129-055520_Samsung Internet.jpg](https://github.com/amvstrm/api/assets/45560312/05841e18-3534-41c4-a213-a2793ca9b781)

I'm over the moon 🌙 🌚 ✨️  

Back to patching

**Comment by adgsenpai** [comment]
Okay status update i think the dudes server just got that requests cached :-( still fails.

![image](https://github.com/amvstrm/api/assets/45560312/6e416742-028f-44c3-bc10-0267f6cc550f)

**Comment by adgsenpai** [comment]
Okay guys your really did save my asshole. I think the dev never just update the production api etc.

My assumption his that the vercel account has the CD/CI updates. i do see the other guys website is back up. Just need to sort out my self hosting in the main while gonna leverage his domain to buy time lol. Thanks guys

```
addEventListener('fetch', event => {
  event.respondWith(handleRequest(event.request));
});

async function handleRequest(request) {
  const url = new URL(request.url);
  const apiURL = `https://api-amvstrm.vercel.app/${url.pathname}`;

  let response;
  switch (request.method) {
    case 'GET':
      response = await fetch(apiURL, { method: 'GET' });
      break;
    case 'POST':
      response = await fetch(apiURL, {
        method: 'POST',
        headers: request.headers,
        body: await request.text()
      });
      break;
    default:
      return new Response('Method not allowed', { status: 405 });
  }

  // Add CORS headers to the response
  const headers = new Headers(response.headers);
  headers.set('Access-Control-Allow-Origin', 'https://anime.adgstudios.co.za');
  headers.set('Access-Control-Allow-Methods', 'GET, POST, OPTIONS');
  headers.set('Access-Control-Allow-Headers', request.headers.get('Access-Control-Request-Headers'));

  // Create a new response with the added headers
  return new Response(response.body, {
    status: response.status,
    statusText: response.statusText,
    headers: headers
  });
}

```

My cloudflare worker code

**Comment by adgsenpai** [comment]
This route is broken 

![image](https://github.com/amvstrm/api/assets/45560312/ef5b8ec6-7a2c-4ce6-87f7-713c1595ef6a)

**Comment by adgsenpai** [comment]
![image](https://github.com/amvstrm/api/assets/45560312/cf1c066c-b103-4fd6-bd9a-2f22b3bf78ee)

Streaming works

**Comment by adgsenpai** [comment]
Everything is working 100%. Thanks to whatever people who contributed! This repo can be closed!

**Comment by NYT92** [comment]
I already deploy my API with the new gogoanime domain both prod and public API, It seem that the data might be cache by the browser. Everything is working fine now.
