### ISSUE TITLE
cannot deploy on vercel

### ISSUE THREAD

**Issue by Badaryman** [amvstrm/api#24]
![image](https://github.com/amvstrm/api/assets/154390732/3d719055-2c3c-4315-8e17-03d33d1a5e8b)

![image](https://github.com/amvstrm/api/assets/154390732/1f8d9707-c457-4c9d-aac7-d034d1077be9)

this right?

**Comment by Badaryman** [comment]
![image](https://github.com/amvstrm/api/assets/154390732/b74c3934-9d33-4a5e-88f7-682e240c9cb2)
![image](https://github.com/amvstrm/api/assets/154390732/fab9473f-eb9e-4a91-a09f-53e7c1a81bbf)
![image](https://github.com/amvstrm/api/assets/154390732/5f72fb31-35b6-4549-b4ed-f4411d8f9c1e)

**Comment by NYT92** [comment]
It is indeed correct but if you using the Deta version, you should consider use other providers because I have updated the code yet.

You can use our official one ''https://api.amvstr.me/''

**Comment by Badaryman** [comment]
https://api-self-eight.vercel.app/

this is the api i deployed using manual deploy idk why it isnt working

**Comment by Badaryman** [comment]
[cli.txt](https://github.com/amvstrm/api/files/13830762/cli.txt)

this how i deployed it

**Comment by Badaryman** [comment]
> It is indeed correct but if you using the Deta version, you should consider host the API to other providers because I have not updated the code yet.
> 
> You can use our official one **https://api.amvstr.me/**
> 
> You can deploy the API to vercel too and use it on your hosted amvstrm.

wamt to host mine on vercel

**Comment by NYT92** [comment]
You need to rename ``.env.example`` to ``.env`` because without these, the app cannot work

**Comment by Badaryman** [comment]
> You need to rename `.env.example` to `.env` because without these, the app cannot work

![image](https://github.com/amvstrm/api/assets/154390732/edbc7b7d-65ac-49e2-abce-08cb936331b3)

**Comment by Badaryman** [comment]
RATE_LIMIT=300
ALLOWLIST=https://example.com,https://example2.com
BLOCK_WITH_CORS=false
SENTRY_DSN_URL=
PORT=8080
USE_REDIS=false
REDIS_APP_URL=

**Comment by NYT92** [comment]
It should be like that and now try to deploy it to vercel or test it locally 

You can visit the docs for more info
https://docs.amvstr.me/

**Comment by Badaryman** [comment]
![image](https://github.com/amvstrm/api/assets/154390732/603c5fe2-7ce7-44d6-b0df-134e6cc58192)

works now on local the only problem is when i deploy it on vercel

**Comment by NYT92** [comment]
You need to manually add env variable to the project or copy it and paste to the env area and it will automatically added for you in vercel.

**Comment by Badaryman** [comment]
this
API_URL= <Your API URL or Our default API URL>
VERSION=v2 <Default version>


not this right?
RATE_LIMIT=300
ALLOWLIST=https://example.com,https://example2.com
BLOCK_WITH_CORS=false
SENTRY_DSN_URL=
PORT=8080
USE_REDIS=false
REDIS_APP_URL=

**Comment by Badaryman** [comment]
https://[api-self-eight.vercel.app](https://api-self-eight.vercel.app/)/

check now bro

**Comment by NYT92** [comment]
> this
> API_URL= <Your API URL or Our default API URL>
> VERSION=v2 <Default version>
> 
> 
> not this right?
> RATE_LIMIT=300
> ALLOWLIST=https://example.com,https://example2.com
> BLOCK_WITH_CORS=false
> SENTRY_DSN_URL=
> PORT=8080
> USE_REDIS=false
> REDIS_APP_URL=
> 

They are both different the top one is where you put the API URL to the frontend and the down one is for backend

**Comment by Badaryman** [comment]
> > this
> > API_URL= 
> > VERSION=v2 
> > not this right?
> > RATE_LIMIT=300
> > ALLOWLIST=https://example.com,https://example2.com
> > BLOCK_WITH_CORS=false
> > SENTRY_DSN_URL=
> > PORT=8080
> > USE_REDIS=false
> > REDIS_APP_URL=
> 
> They are both different the top one is where you put the API URL to the frontend and the down one is for backend

so i both?

**Comment by NYT92** [comment]
They are both require env.

Frontend just need API URL and version and Backend just need those configuration in the env and you done.

Since you already deployed the API, you can edit the frontend env and add your own API one then redeploy it.

If you got any problems, I will help...

**Comment by Badaryman** [comment]
https://amvstrm-sand.vercel.app/

check bro @NYT92

**Comment by NYT92** [comment]
Yes, It works and you can use it now.

**Comment by Badaryman** [comment]
tysm

**Comment by Badaryman** [comment]
@NYT92 

![Screenshot_2024-01-05-02-15-35-307_com android chrome](https://github.com/amvstrm/api/assets/154390732/75aee8b6-75a8-46cb-a0ff-c31c46e9948c)
![Screenshot_2024-01-05-02-15-41-671_com android chrome](https://github.com/amvstrm/api/assets/154390732/27741fb1-9fa5-4a4b-acfc-e305e0fd2793)

**Comment by Badaryman** [comment]
https://prnt.sc/ldEpNIA0qJUf

**Comment by Badaryman** [comment]
So basically the site im using uses both v1 and v2 of the api to work but when i tried to use my hosted api for v1 and v2 there is an undefined in the url

**Comment by Badaryman** [comment]
Please Help @NYT92

**Comment by Badaryman** [comment]
this is the site

https://test-xi-indol-37.vercel.app/

this is the api
https://vercel.com/badarymans-projects/api

**Comment by NYT92** [comment]
Idk what is the problem but we should move it to discussions area.

**Comment by Badaryman** [comment]
where @NYT92

**Comment by NYT92** [comment]
Just create new discussions here https://github.com/orgs/amvstrm/discussions/categories/discussions
