### ISSUE TITLE
Donation of Linux Server

### ISSUE THREAD

**Issue by adgsenpai** [amvstrm/api#31]
Hey buddy i am wondering if i can donate you a Linux box to host this API for the guys. I can give you reverse proxies also if needed.

My website is anime.adgstudios.co.za i love your project and I leverage your one to enable streaming on the website. Let me know if you are interested on the offer!

**Comment by NYT92** [comment]
That would help me a lot for hosting API since I really want to keep the cost down as much as possible.

**Comment by adgsenpai** [comment]
> That would help me a lot for hosting API since I really want to keep the cost down as much as possible.

How can i get your contact details? You can add me on Discord? My username is @adgsenpai 

Whatsapp: +27605224922
Email: adg@adgstudios.co.za
