### ISSUE TITLE
No response for streaming api 

### ISSUE THREAD

**Issue by anime-kun32** [amvstrm/api#32]
anytime i want to use the v2 version for stream i get route not found

**Comment by NYT92** [comment]
Can you tell me what route are you trying to access and error messages?

**Comment by anime-kun32** [comment]
the gogo anime router for the /stream

**Comment by anime-kun32** [comment]
the url is this https://[api-p1xr.vercel.app/api/v2/stream?id=sonic-x-episode-1&data_src=gogo](https://api-p1xr.vercel.app/api/v2/stream?id=sonic-x-episode-1&data_src=gogo) and then the response is this 
{
    "code": 404,
    "message": "Route not found"
}
i was using the documentation page which is here https://docsapi-amvstrm.pages.dev/#/operations/get-stream

**Comment by NYT92** [comment]
We have updated the API from using query to using params. The docs you referring to is now obsoleted. 
You should be using `/api/v2/stream/<gogo anime episode id>` instead. We might provide a new docs later on with better schema and more information soon.

**Comment by anime-kun32** [comment]
Thanks
